layout_spectrum: 0.8635360906074875
typography_spectrum: 0.31043203077730863
color:
  brandStrength: 0.6427553507352782
  lightness: 0.7474069666270499
  saturation: 0.3076635919285403
  rhythmicContrast: 0.6058765557898891
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
author:
  name: TeamB
  email: earl.blacklock@yorkvilleu.com
name: PSYC6104teamb
url: 'https://thegrid.ai/PSYC6104teamb'
navigation:
  - name: Terry Meikle
    id: 2dbb7ffd-d2fe-41fd-b129-0720e02d2957
    type: content
title: Psyc 6104 Team B
content: []
description: 'T Cunningham, T Meikle, K Decelle, and E Blacklock'
purpose:
  - type: contact
    url: 'mailto:earl.blacklock@gmail.com'
    label: Contact me
github: true
