typography_spectrum: 0.31043203077730863
color:
  brandStrength: 0.6427553507352782
  lightness: 0.7474069666270499
  saturation: 0.3076635919285403
  rhythmicContrast: 0.6058765557898891
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.8635360906074875
author:
  name: TeamB
  email: earl.blacklock@yorkvilleu.com
name: PSYC6104TeamB
url: 'https://thegrid.ai/PSYC6104teamb'
navigation:
  - name: Earl Blacklock
    id: 8ca4992e-af2e-47b8-a944-217ac440ca86
    type: content
  - name: Terry Meikle
    id: 2b622a27-a895-421c-ab42-abf9c7a5f691
    type: content
title: Psyc 6104 Team B
content: []
description: 'T Cunningham, T Meikle, K Decelle, and E Blacklock'
purpose:
  - type: contact
    url: 'mailto:earl.blacklock@gmail.com'
    label: Contact me
